### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by StevenClontz**
https://groups.google.com/g/pretext-support/c/5EhXaz_MHwA/m/iRtDPVbRCAAJ

Accepting this PR (once it's ready) will fix your main branch, as well as address the issues discussed in -support above.

### CODE REVIEW

**Comment by StevenClontz** [comment]
It turns out that your source was perfectly fine; we just don't install SageMath by default in a new PreTeXt-CLI configured Codespace. (I'm proposing we change that in future versions: https://github.com/PreTeXtBook/pretext-cli/pull/764 )

Anyway, you should be able to merge this PR into your main branch. Then I suggest you delete the old codespace, then create a new codespace on main.

Finally: your main branch got out of sync with your codespace when you manually uploaded a file via GitHub.com: https://github.com/johnestesmath/onboard/commit/444dbbd6f9abbd6f615d27dfb01ebdd085ad448b If you're using a Codespace, you should stick to using the Codespace to work on your project, so you don't have to merge changes from different sources later.

**Comment by johnestesmath** [comment]
Great. Thanks so much! I think I followed your steps correctly. Will this also solve the youtube playback problems?

**Comment by StevenClontz** [comment]
YouTube issue slipped by me, let me see

**Comment by StevenClontz** [comment]
What YouTube video are you trying to embed?

**Comment by johnestesmath** [comment]
You can see in the sec-test.ptx, I'm trying to embed a Ted ED video on pascal's triangle: https://www.youtube.com/watch?v=XMriWTvPXHI&t=6s

**Pull request merged**
